version: "3.8"
services:
  wa-agent-api:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped

    volumes:
      - ./app:/app/app
      - ./.env:/app/.env
